### ISSUE TITLE
Clarify spec around @NestedLRA when no parent LRA present.

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-lra#117] opened 2019-03-18 08:16 UTC
See also https://github.com/eclipse/microprofile-sandbox/issues/46.

Within the spec it isn't defined what happens in case a `@NestedLRA`annotated JAX-RS endpoint is called when no parent LRA is present.

**Comment by mmusgrov** [comment] 2019-03-19 12:17
The javadoc for @NestedLRA does already state this behaviour:

{quote}
 * Used on the interface or class. Defines that the container will create
 * a new LRA for each method invocation, regardless of whether or not there is
 * already an LRA associated with the caller. These LRAs will then
 * either be top-level LRAs or nested automatically depending upon the
 * context within which they are created.
{quote}

and the spec doc states:

{quote}
The definitive documentation for how the annotations affect the behaviour of a running program is
the javadoc and this specification should be read in conjunction with it. The annotations are
defined in the org.eclipse.microprofile.lra.annotation package:
...
{quote}

and there is a brief reference to this behaviour in section  3.2.4. Nesting LRAs of the spec doc:

{quote}
But if there is no LRA present then a new top level LRA is started ...
{quote}

**Comment by mmusgrov** [comment] 2019-03-24 12:16
I close issue #123 since it is a duplicate of this one. To the second point raised by @nmcl regarding "what happens if an LRA isn't active when @NestedLRA is called": the answer is that a new top level LRA will be started which is documented in the javadoc and in the spec doc:

https://github.com/eclipse/microprofile-lra/blob/master/api/src/main/java/org/eclipse/microprofile/lra/annotation/ws/rs/NestedLRA.java#L46

and in section 3.25 of the spec:

https://github.com/eclipse/microprofile-lra/blob/master/spec/src/main/asciidoc/microprofile-lra-spec.adoc#324-nesting-lras

**Comment by ochaloup** [comment] 2019-03-25 10:45
As we talked at the meeting I read through the [current javadoc of @NestedLRA](https://github.com/eclipse/microprofile-lra/blob/master/api/src/main/java/org/eclipse/microprofile/lra/annotation/ws/rs/NestedLRA.java#L46) and I think there is no functional issue with adding the nested lra as the type.

And I like it from the user perspective. I think it makes sense.

I would only add that maybe there will be need to add some more information to say how the other `@LRA` attributes interact with the `NESTED` type. Like adding info that the `cancelOnFamily` cancels the nested LRA but not the parent one or if `end = false` make sense.
```
@LRA(type = NESTED, end = false)
```

**Closed** 2019-04-26 10:14 UTC
Labels: PR sent
