### ISSUE TITLE
Requirement of @LRA on @Leave annotated method: Clarify

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-lra#122] opened 2019-03-20 10:08 UTC
Javadoc for `@Leave` for example 

`invoking such a method in the context of the same LRA that it has joined will result in the resource leaving the LRA (ie it will not receive any callbacks when the LRA is later closed or cancelled)
`

So, in order to know which is the LRA, the request needs to contain the LRA_HTTP_HEADER ,identifying the LRA id.
So there is no need to join the same LRA before the functionality of @Leave can be performed.

Using LRA can create even more confusion and errors, for example, what should happen in this case?
```
@LRA(type=REQUIRES_NEW)
@Leave
```

**Comment by xstefank** [comment] 2019-03-20 10:21
@rdebusscher exactly and I think we already don't require `@LRA` on `@Leave` methods [1] - the TCK test is already passing.

IMO `@Leave` should work only with LRA_HTTP_HEADER so that LRA_HTTP_HEADER should be present on invocation to indicate which LRA is concerned. If the header is not provided by user invoking the leave method than current context should be used and injected by the implementation to LRA_HTTP_HEADER.

[1] https://github.com/eclipse/microprofile-lra/blob/master/tck/src/main/java/org/eclipse/microprofile/lra/tck/participant/api/LraController.java#L157

**Comment by rdebusscher** [comment] 2019-03-20 10:36
@xstefank I saw your comment on a PR and based on that I created this issue. (because your comment was not linked to the PR content but valid)

**Comment by mmusgrov** [comment] 2019-03-20 16:05
@rdebusscher The annotations are for the end user to define his transaction boundaries. If there is no such annotation then the implementation is allowed to ignore or remove the header ie it cannot be relied upon to be present without the LRA annotation. This rule ought to make using spec less error prone / easier to use.

But I will update the spec to make this clear. (Remark: The header is still useful to clients since they are allowed to manually add the header in order to propagate the context to target resource methods that are annotated with @LRA, I will make sure that is clear too).

With regards to @xstefank comment about the test resource - that is a bug and we need a test to ensure that the implementation ignores the context if there is no @LRA annotation.

**Comment by mmusgrov** [comment] 2019-03-20 17:04
@rdebusscher But to answer your question: typically the application would use SUPPORTS, REQUIRED or MANDATORY. I did want to have the annotations driving everything but if we cannot do that by simply documenting the expected behaviour then, yes, let's nail down the semantics of the header along the lines that Martin assumed.

**Comment by mmusgrov** [comment] 2019-04-13 08:47
Re-opened for TCK tests

**Comment by mmusgrov** [comment] 2019-04-18 09:56
Fixed with PR's 124 and 132

**Closed by mmusgrov** 2019-04-18 09:56 UTC
